version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: 'newnakashima/nksm-in-net:latest'
    steps:
      - checkout
      - run:
          name: 'Elm build'
          command: 'elm make src/main.elm --output=dist/js/main.js'
  deploy:
    docker:
      - image: 'newnakashima/nksm-in-net:latest'
    steps:
      - checkout
      - run:
          name: 'Elm build'
          command: 'elm make src/main.elm --output=dist/js/main.js'
      - aws-s3/sync:
          from: dist
          to: 's3://nksm.in.net/'
          overwrite: true

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
