version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'

    steps:
      - checkout

      - aws-s3/sync:
          from: dist
          to: 's3://nksm.in.net/'
          overwrite: true

