version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: 'newnakashima/nksm-in-net:latest'
    steps:
      - checkout
      - run:
          name: 'npm install'
          command: 'npm install'
      - run:
          name: 'npm run build'
          command: 'npm run build'
  deploy:
    docker:
      - image: 'newnakashima/nksm-in-net:latest'
    steps:
      - checkout
      - run:
          name: 'npm install'
          command: 'npm install'
      - run:
          name: 'npm run build'
          command: 'npm run build'
      - aws-s3/sync:
          from: dist
          to: 's3://nksm.in.net/'
          overwrite: true
      - run:
          name: 'invalidate cloudfront cache'
          command: 'aws cloudfront create-invalidation --distribution-id="E1S9YOK0Q5IK9R" --paths="/*"'

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
