module HtmlContents.Prices exposing (prices)

import Browser
import ContentsCommon exposing (..)
import Html exposing (..)
import Html.Attributes exposing (..)
import Msg exposing (Msg(..))


prices : Browser.Document Msg
prices =
    { title = "Prices | " ++ pageTitle
    , body =
        [ header []
            [ h1 [] [ text "Prices" ]
            ]
        , main_ []
            [ p [] [ text "価格は全て税別です。サーバー料金等の経費は除きます。" ]
            , h2 [] [ text "見積料" ]
            , p [] [ text "工数、工期、費用をお見積りします。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "工期が2ヶ月以内のもの" ]
                , div [ class "flex-item" ] [ text "無料" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "工期が2ヶ月を超えるもの" ]
                , div [ class "flex-item" ] [ text "工期1ヶ月分あたり5万円" ]
                ]
            , h2 [] [ text "WEB開発" ]
            , p [] [ text "WEBサービスの開発を行います。下記の機能を持つサイトを想定しています。" ]
            , p [] [ text "プロトタイピングでは一部の機能のみ実装します。" ]
            , ul [ class "application-spec"]
                [ li [] [ text "ユーザーログイン機能" ]
                , li [] [ text "ユーザー投稿機能" ]
                , li [] [ text "ユーザーフォロー機能" ]
                , li [] [ text "タイムライン機能" ]
                , li [] [ text "お気に入り機能" ]
                , li [] [ text "ダイレクトメッセージ機能" ]
                , li [] [ text "管理画面" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "プロトタイピング" ]
                , div [ class "flex-item" ] [ text "60万円" ]
                ]

            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "サービス構築からリリースまで" ]
                , div [ class "flex-item" ] [ text "200万円" ]
                ]
            , h2 [] [ text "スマートフォンアプリ開発" ]
            , p [] [ text "スマートフォンアプリの開発を行います。下記の機能を持つアプリを想定しています。" ]
            , p [] [ text "プロトタイピングでは一部の機能のみ実装します。" ]
            , ul [ class "application-spec"]
                [ li [] [ text "ユーザーログイン機能" ]
                , li [] [ text "ユーザー投稿機能" ]
                , li [] [ text "ユーザーフォロー機能" ]
                , li [] [ text "タイムライン機能" ]
                , li [] [ text "お気に入り機能" ]
                , li [] [ text "カメラ機能" ]
                , li [] [ text "ダイレクトメッセージ機能" ]
                , li [] [ text "管理画面（管理者用WEBサイト）" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "プロトタイピング" ]
                , div [ class "flex-item" ] [ text "100万円" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "サービス構築からリリースまで" ]
                , div [ class "flex-item" ] [ text "300万円" ]
                ]
            , h2 [] [ text "AWS環境構築" ]
            , p [] [ text "AWSの環境を構築します。EC2、Lambda、Fargateなどを使用します。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "初期構築" ]
                , div [ class "flex-item" ] [ text "60万円" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "保守" ]
                , div [ class "flex-item" ] [ text "5万円/月" ]
                ]
            , h2 [] [ text "SES" ]
            , p [] [ text "フルリモートの案件のみお受けします。条件によりお断りさせていただくことがあります。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "1人月" ]
                , div [ class "flex-item" ] [ text "60万円" ]
                ]
            ]
        ]
    }
