module HtmlContents.Prices exposing (prices)

import Browser
import ContentsCommon exposing (..)
import Html exposing (..)
import Html.Attributes exposing (..)
import Msg exposing (Msg(..))


prices : Browser.Document Msg
prices =
    { title = "Prices | " ++ pageTitle
    , body =
        [ header []
            [ h1 [] [ text "Prices" ]
            ]
        , main_ []
            [ p [] [ text "価格は全て税別です。サーバー料金等の経費は除きます。" ]
            , p [] [ text "納品する成果物は下記です。" ]
            , ul [ class "work-spec" ]
                [ li [] [ text "機能説明ドキュメント（Wiki形式）" ]
                , li [] [ text "テーブル定義" ]
                , li [] [ text "ソースコード一式" ]
                , li [] [ text "本番・ステージング・開発環境サーバー一式" ]
                ]
            , p [ style "margin-top" ".5rem", style "font-weight" "bold" ] [ text "※ ソースコードの所有権を私に頂ける場合はトータルの金額から20%お値引きします。" ]
            , p [ style "margin-top" ".5rem", style "font-weight" "bold" ] [ text "※ 期間を明確に定めない秘密保持契約（契約期間の自動更新を含む）を結ぶ場合は、トータルの金額に50%割増となります。"]
            , p [ style "margin-top" ".5rem", style "font-weight" "bold" ] [ text "※ 期間を定めた秘密保持契約を結ぶ場合は、トータルの金額の5%を毎月請求させて頂きます。"]
            , p [ style "margin-top" ".5rem", style "font-weight" "bold" ] [ text "※ 秘密の範囲を明確に定めない秘密保持契約を結ぶ場合は、トータルの金額に50%割増となります。"]
            , p [ style "margin-top" ".5rem", style "font-weight" "bold" ] [ text "※ 秘密の範囲を定めた秘密保持契約を結ぶ場合は、トータルの金額に50%に秘密の範囲の割合をかけた金額が割増となります。"]

            , h2 [] [ text "見積料" ]
            , p [] [ text "工数、工期、費用をお見積りします。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "工期が2ヶ月以内のもの" ]
                , div [ class "flex-item" ] [ text "無料" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "工期が2ヶ月を超えるもの" ]
                , div [ class "flex-item" ] [ text "工期1ヶ月分あたり10万円" ]
                ]
            , h2 [] [ text "Web開発" ]
            , p [] [ text "Webサービスの開発を行います。下記の機能を持つサイトを想定しています。" ]
            , p [] [ text "プロトタイピングでは一部の機能のみ実装します。" ]
            , ul [ class "application-spec" ]
                [ li [] [ text "ユーザーログイン機能" ]
                , li [] [ text "ユーザー投稿機能" ]
                , li [] [ text "ユーザーフォロー機能" ]
                , li [] [ text "タイムライン機能" ]
                , li [] [ text "お気に入り機能" ]
                , li [] [ text "ダイレクトメッセージ機能" ]
                , li [] [ text "管理画面" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "プロトタイピング" ]
                , div [ class "flex-item" ] [ text "100万円" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "サービス構築からリリースまで" ]
                , div [ class "flex-item" ] [ text "300万円" ]
                ]
            , h2 [] [ text "スマートフォンアプリ開発" ]
            , p [] [ text "スマートフォンアプリの開発を行います。下記の機能を持つアプリを想定しています。" ]
            , p [] [ text "プロトタイピングでは一部の機能のみ実装します。" ]
            , ul [ class "application-spec" ]
                [ li [] [ text "ユーザーログイン機能" ]
                , li [] [ text "ユーザー投稿機能" ]
                , li [] [ text "ユーザーフォロー機能" ]
                , li [] [ text "タイムライン機能" ]
                , li [] [ text "お気に入り機能" ]
                , li [] [ text "カメラ機能" ]
                , li [] [ text "ダイレクトメッセージ機能" ]
                , li [] [ text "管理画面（管理者用Webサイト）" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "プロトタイピング" ]
                , div [ class "flex-item" ] [ text "120万円" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "サービス構築からリリースまで" ]
                , div [ class "flex-item" ] [ text "360万円" ]
                ]
            , h2 [] [ text "AWS環境構築" ]
            , p [] [ text "AWSの環境を構築します。EC2、Lambda、Fargateなどを使用します。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "初期構築" ]
                , div [ class "flex-item" ] [ text "80万円" ]
                ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "保守" ]
                , div [ class "flex-item" ] [ text "10万円/月" ]
                ]
            , h2 [] [ text "SES" ]
            , p [] [ text "フルリモートの案件のみお受けします。条件によりお断りさせていただくことがあります。" ]
            , div [ class "flex-row" ]
                [ div [ class "flex-item" ] [ text "1人月（140-180時間）" ]
                , div [ class "flex-item" ] [ text "80万円" ]
                ]
            ]
        ]
    }
